### ISSUE TITLE
Clarify trademark status of diceware

### ISSUE THREAD

**Issue by simonft** [ulif/diceware#48]
Both the LICENSE file and http://world.std.com/~reinhold/diceware.html state that "diceware" is a trademark of Arnold G. Reinhold. Did he grant permission for the name to be used in this project? If so, under what conditions?

**Comment by ulif** [comment]
No, not yet. I asked for permission two times, when starting this project, but received no answer at all. I _might_ have used the wrong e-mail address, but not shure about that, though.

Just now started another try and requested a permission from  the address listed in the footers of http://diceware.com.

I will tell here, when I got an answer from Mr. Reinhold. Thanks for reminding me!

**Comment by drebs** [comment]
Just to inform, Diceware [has been marked for autoremoval from Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892494) because of this. It will not be included in the next Debian version if this issue is not solved (either by getting permission or changing the name of the program, I guess).

**Comment by ulif** [comment]
Wow, a (legally mainly irrelevant) construct like an unregistered "common law" trademark can kick long running projects from Debian? Seriously? Even with no one complaining (except Mr. Fondrie-Teitler, maybe)? Not very helpful.

Since Monday I got the explicit permission from Mr. Arnold. So, while the legal aspect should be fixed by this, I am a bit confused about this procedere and must take my time to overthink the future of the whole project.

**Comment by ulif** [comment]
It would also have been nice to get this info from Mr. Fondrie-Teitler.

**Comment by simonft** [comment]
Sorry if there has been any miscommunication! I'm not on expert on Debian policy, but my understanding is the trademark issue is potentially problematic. In the US, even unregistered trademarks can carry weight. It would be pretty disruptive if this package needed to be removed from stable because Arnold Reinhold decided to assert his trademark.

My intent in filing the bug was not to get diceware removed from Debian. I didn't even know it had been marked for autodeletion until I saw the comment in this issue. I chatted with @drebs before filing the Debian bug, and we decided it was reasonable to file one to ensure it didn't get forgotten. I should have given you a heads up that I filed the bug, and noted my thoughts on the severity. 

I'm glad the trademark issue has been resolved! Thanks for your work on this project.

**Comment by ulif** [comment]
Sorry @simonft and @drebs for being so rude yesterday. Please imagine sitting with your first coffee of the day, checking your inbox and reading 

  "Good morning, all your projects are to be destroyed. Destruction in three - two - one...."

Now I see that this was not intended by anyone, so everything is fine, I hope, and would like to apologize for my harsh words.

I still see problems ahead with the strict Debian policy and are not sure, whether it is really meant that strict. While I support Debian strongly for strictness in copyright-policy, I cannot do the same for trademark issues -- but this should be discussed somewhere else and is luckily not an issue of 'diceware' any more.

Back to the main issue. As told already, I am happy to provide a permission from Mr. Reinhold to use the name "Diceware".

For the logs and FYI I will quote the conditions from Mr. Reinhold here:

> I therefore grant you permission to use the Diceware trademark subject to the following conditions:
> 
> 1. You continue to use Python’s system.random class as the default source of randomness in generating passwords.
> 
> 2. You continue to provide an option for direct entry of dice results.
> 
> 3. Permission is limited to your command line tool. Other applications, such as smartphone apps, require additional permission.
> 
> 4. You include a statement in the source code, version text and your documentation that “Diceware is a trademark of Arnold G Reinhold, used with permission."

Oh, and Mr. Reinhold also encourages us to add more wordlists. We should really make some progress in that field in the next weeks. @drebs, is Luciano still interested in providing a portugese list? That would be awesome.

@drebs, my next commit should automatically close this issue. I hope that we can remove the autoremoval from Debian then as well.

**Comment by pabs3** [comment]
AFAICT, system.random does not seem to exist in Python. I guess that refers to random.SystemRandom instead? If so the license needs to be updated.

I am not a lawyer but this trademark license looks incompatible with the GNU GPL so I think it will render this project non-distributable if distributors are required to comply with both the GNU GPL and the trademark license.

The restrictions on modification don't conflict with the DFSG item 3 because of the option of renaming the software (DFSG item 4), but having to do that would probably be inconvenient for both Debian and yourself.

That said, it is unlikely Debian would do anything that violates the trademark license.

**Comment by drebs** [comment]
pabs3 commented a day ago
> AFAICT, system.random does not seem to exist in Python. I guess that refers to random.SystemRandom instead? If so the license needs to be updated.

Seems to me you are correct.

> I am not a lawyer but this trademark license looks incompatible with the GNU GPL so I think it will render this project non-distributable if distributors are required to comply with both the GNU GPL and the trademark license.

Can you clarify what is the possible incompatibility between the 4-item "diceware" trademark use conditions and the licensing of this specific implementation of diceware as GPL that would make distribution impossible?

The GPLv3 explicitelly mentions the possibility of "Additional Terms" that can "supplement" the terms of the GPLv3 itself with terms "declining to grant rights under trademark law for use of some trade names, trademarks, or service marks".

Wouldn't it just be the case of creating an "Additional Terms" section in the diceware version of the GPLv3 itself adding the (corrected) 4-items above as a condition to keep using the name?

> The restrictions on modification don't conflict with the DFSG item 3 because of the option of renaming the software (DFSG item 4), but having to do that would probably be inconvenient for both Debian and yourself.

As I understand it, maintaining the "diceware" name here is important because:

- The creator of this implementation wants it to be known as an implementation of the diceware system for generating secure passphrases, because the system is mathematically proved to generate passphrases with certain security/entropy characteristics.
- The creator of the system wants to make sure that if an implementation uses its name then it does actually have security/entropy characteristics that the mathematical system provides. That is why the trademark owner wants to have restrict use based on characteristics of the implementation (i.e. the use of real dice and the default use of specific sources of pseudorandom numbers).
- Everyone wants the wide public to be able to generate and use passphrases that are both easy to remember and secure. That is the whole point of different people having created the mathematical system, the implementation, and the Debian package.

So it seems to me we might have all conditions needed to keep using the name and packaging it in Debian:

- The implementation developer wants to use the name.
- The trademark owner allows the use of the trademark for this specific implementation.
- The GPLv3 allows for "Additional Terms" that can make it clear the conditions of use of the trademark.
- GPLv3 is compliant with DFSG.

Is there something missing?

**Comment by ulif** [comment]
>>    AFAICT, system.random does not seem to exist in Python. I guess that refers to random.SystemRandom instead? If so the license needs to be updated.

> Seems to me you are correct.

Right. Mr. Reinhold wants to ensure, no self-brewed crypto is used by default. This makes a lot of sense to me. I will ask him for a fixed permission.

For the other issue I'd go along with @drebs . There are BTW many projects in Debian, like zotero, wordpress, etc., that carry much stricter trademark conditions. And they still live in Debian :)

**Comment by pabs3** [comment]
Hmm, I wasn't aware of the trademark provisions of GPLv3.
I guess that is fine then.

-- 
bye,
pabs

http://bonedaddy.net/pabs3/
